version: '3.8'

services:
  autonav:
    image: jatinvpatil/autonav:latest
    command: >
      /opt/venv/bin/uvicorn index:app --host 0.0.0.0 --port 8000
    network_mode: "host"
    ipc: host
    user: "1000:1000"
    privileged: true 
    devices:
      # - "/dev/bno055:/dev/bno055"
      - /dev/lidar:/dev/lidar_x4
      
    volumes:
      - /dev/bno055:/dev/bno055
      - /dev/robotcam:/dev/robotcam
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      # - "~/AutoNav:/colcon_ws/src"
      - "~/AutoNav/WebServer:/WebServer"
      - /var/run/dbus:/var/run/dbus  # Required for nmcli
      - /run/systemd:/run/systemd
      - /run/dbus:/run/dbus
      - /etc/NetworkManager:/etc/NetworkManager
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/sudoers.d:/etc/sudoers.d 
    restart: unless-stopped


  micro_ros:
    image: microros/micro-ros-agent:kilted
    command: serial --dev /dev/esp32
    privileged: true
    network_mode: host
    ipc: host
    user: "1000:1000"
    volumes:
      - /dev/esp32:/dev/esp32
      - ~/AutoNav/fastdds.xml:/fastdds.xml
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTDDS_DEFAULT_PROFILES_FILE=/fastdds.xml
    restart: unless-stopped

  
  mongodb:
    image: mongo:4.4.18
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb_data_test:/data/db
    restart: unless-stopped
    # mongodb://localhost:27017

