version: '3.8'

services:
  autonav:
    image: jatinvpatil/autonav:latest
    command: bash -c "source /colcon_ws/install/setup.bash && colcon build --symlink-install && source /colcon_ws/install/setup.bash && ros2 launch autonav_firmware autonav_bringup.launch.py"
    network_mode: "host"
    devices:
      - "/dev/bno055:/dev/bno055"
      - "/dev/lidar:/dev/lidar_x4"
    volumes:
      - "~/colcon_ws/src/AutoNav:/colcon_ws/src"

  micro_ros:
    image: microros/micro-ros-agent:humble
    command: serial --dev /dev/ttyesp32
    privileged: true
    network_mode: host
    volumes:
      - /dev/esp32:/dev/ttyesp32

  navigation:
    container_name: navigation
    extends: autonav
    command: bash -c "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && colcon build --symlink-install --packages-select autonav_navigation && source /colcon_ws/install/setup.bash && ros2 launch autonav_navigation navigation.launch.py"
    stdin_open: true
    tty: true
    network_mode: "host"
    ipc: host
    privileged: true

  slam:
    container_name: slam
    network_mode: "host"
    extends: autonav
    command: bash -c "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && source /colcon_ws/install/setup.bash && ros2 launch autonav_navigation slam.launch.py"

  cartographer:
    container_name: cartographer
    network_mode: "host"
    extends: autonav
    command: bash -c "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && source /colcon_ws/install/setup.bash && ros2 launch autonav_navigation cartographer.launch.py"

  save_map:
    container_name: save_map
    extends: autonav
    command: bash -c "source /colcon_ws/install/setup.bash && ros2 launch autonav_navigation save_map.launch.py"
    stdin_open: true
    tty: true
    network_mode: "host"
    ipc: host
    privileged: true

  rviz:
    container_name: rviz
    network_mode: "host"
    image: jatinvpatil/autonav:latest
    command: bash -c "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && source /colcon_ws/install/setup.bash && ros2 launch autonav_bringup view_rviz.launch.py rviz:=True"
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority

  control:
    container_name: control
    network_mode: "host"
    image: jatinvpatil/autonav:latest
    command: bash -c "source /colcon_ws/install/setup.bash && ros2 run autonav_controller control.py"
    stdin_open: true
    tty: true
    volumes:
      - "~/colcon_ws/src/AutoNav:/colcon_ws/src"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    ipc: host
    privileged: true

  camera:
    image: jatinvpatil/autonav:latest
    command: bash -c "source /colcon_ws/install/setup.bash && ros2 run autonav_perception camera_publish.py"
    network_mode: "host"
    ipc: host
    privileged: true
    devices:
      - "/dev/media0:/dev/media0"
      - "/dev/media1:/dev/media1"
      - "/dev/media2:/dev/media2"
      - "/dev/media3:/dev/media3"
      - "/dev/video1:/dev/video1"
      - "/dev/video0:/dev/video0"
    volumes:
      - "~/colcon_ws/src/AutoNav:/colcon_ws/src"

  camera_view:
    container_name: camera_view
    network_mode: "host"
    image: jatinvpatil/autonav:latest
    command: bash -c "source /colcon_ws/install/setup.bash && ros2 run autonav_perception camera_subscribe.py"
    volumes:
      - "~/colcon_ws/src/AutoNav:/colcon_ws/src"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    ipc: host
    privileged: true

  rviz_slam:
    container_name: rviz_slam
    network_mode: "host"
    extends: rviz
    command: bash -c "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && source /colcon_ws/install/setup.bash && ros2 launch autonav_bringup view_rviz_slam.launch.py rviz:=True"

  rviz_navigation:
    container_name: rviz_navigation
    network_mode: "host"
    extends: rviz
    command: bash -c "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && source /colcon_ws/install/setup.bash && ros2 launch autonav_bringup view_rviz_navigation.launch.py rviz:=True"

  rviz_cartographer:
    container_name: rviz_cartographer
    network_mode: "host"
    extends: rviz
    command: bash -c "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && source /colcon_ws/install/setup.bash && ros2 launch autonav_bringup view_rviz_cartographer.launch.py rviz:=True"
