version: '3.8'

services:
  autonav:
    image: jatinvpatil/autonav:latest
    command: >
      uvicorn index:app --host 0.0.0.0 --port 8000
    # command: bash -c "source /colcon_ws/install/setup.bash && colcon build --symlink-install && source /colcon_ws/install/setup.bash && ros2 launch autonav_firmware autonav_bringup.launch.py"
    # network_mode: "host"
    devices:
      - "/dev/bno055:/dev/bno055"
      - "/dev/lidar:/dev/lidar_x4"
    ports:
      # - 27017:27017
      - 8000:8000
    volumes:
      - "~/AutoNav:/colcon_ws/src"
      - "~/AutoNav/WebServer:/WebServer"
    restart: unless-stopped

  micro_ros:
    image: microros/micro-ros-agent:humble
    command: serial --dev /dev/ttyesp32
    privileged: true
    # network_mode: host
    volumes:
      - /dev/esp32:/dev/ttyesp32
    restart: unless-stopped
  
  mongodb:
    image: mongo:4.4.18
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb_data:/data/db
    restart: unless-stopped
