name: ROS2 CI

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - foxy
          - galactic
          - rolling
        include:
          # Foxy Fitzroy (June 2020 - May 2023)
          - ros_distribution: foxy
            docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-foxy-ros-base-latest
          # Galactic Geochelone (May 2021 - November 2022)
          - ros_distribution: galactic
            docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
          # Humble Hawksbill (May 2022 - May 2027)
          - ros_distribution: humble
            docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
          # Rolling Ridley  (June 2020 - Present)
          - ros_distribution: rolling
            docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-rolling-ros-base-latest
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: install dependencies
        run: "pip3 install -r ros_ws/src/requirements.txt"
      - name: build and test
        uses: ros-tooling/action-ros-ci@master
        with:
          package-name: bno055
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
