; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = /dev/esp32

board_microros_distro = humble
board_microros_transport = serial
lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino.git#v2.0.8-humble
    https://github.com/micro-ROS/micro_ros_platformio
    https://github.com/Aasim-A/AsyncTimer
    https://github.com/waspinator/AccelStepper
    https://github.com/FastLED/FastLED
    https://github.com/adafruit/Adafruit_NeoPixel
