TrajectoryPlannerROS:
  max_vel_x: 0.6
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.5

  acc_lim_theta: 0.5
  acc_lim_x: 0.4
  acc_lim_y: 0

  holonomic_robot: false
  meter_scoring: true
