
obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.075, -0.130], [-0.075, 0.130], [0.075, 0.130], [0.075, -0.130]]
#robot_radius: 0.105

inflation_radius: 1.0
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: ydlidar_x4_v2_1, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#always_send_full_costmap: true
#combination_methods: 0
