DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.15
  min_vel_x: -0.15

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.2
  min_vel_trans:  0.08

  max_vel_theta: 0.6
  min_vel_theta: 0.1

  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 2.0

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1 # sec
  vx_samples: 3 # units
  vy_samples: 0
  vth_samples: 3
  controller_frequency: 3 #hz

# Trajectory Scoring Parameters
  #meter_scoring: true
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
