DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.8
  min_vel_x: 0.0

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.8
  min_vel_trans:  0.1

  max_vel_theta: 6.0
  min_vel_theta: 0.5
  
  max_rot_vel: 1.5
  min_rot_vel: 0.4

  acc_lim_x: 3.5
  acc_lim_y: 0.0
  acc_lim_theta: 50.0

# Goal Tolerance Parametes
  xy_goal_tolerance: 0
  yaw_goal_tolerance: 0
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.5 # sec
  vx_samples: 20 # units
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 10.0 #hz

# Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.05
  max_scaling_factor: 0.09

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
