controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: false

    autonav_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

autonav_controller:
  ros__parameters:
    type        : diff_drive_controller/DiffDriveController

    use_stamped_vel: false

    left_wheel_names  : ['base2left']
    right_wheel_names : ['base2right']

    publish_rate: 50.0               # default: 50
    pose_covariance_diagonal : [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

    wheel_separation : 0.245
    wheel_radius : 0.04

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    open_loop: false

    position_feedback: true

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.1

    # Base frame_id
    base_frame_id: base_footprint #default: base_link

    # Publish limited velocity
    publish_limited_velocity: false

    # Publish wheel data
    publish_wheel_data: true

    # Publish to TF directly or not
    enable_odom_tf: false

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.3  # m/s
        min_velocity           : -0.3 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.6  # m/s^2
        min_acceleration       : -0.6 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.5  # rad/s
        min_velocity           : -1.5 # m/s
        has_acceleration_limits: true
        max_acceleration       : 3.0  # rad/s^2
        min_acceleration       : -3.0 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 2.5  # rad/s^3

simple_velocity_controller:
  ros__parameters:
    joints:
      - base2left
      - base2right

