controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    autonav_controller:
      type: velocity_controllers/JointGroupVelocityController

autonav_controller:
  ros__parameters:
    joints:
      - base2left
      - base2right
