name: Flutter CI

on:
  push:
    branches: [ "autonav_web" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3" # use your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Build release APK
        run: flutter build apk --release

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/AutoNav.apk

      - name: Upload APK as artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: AutoNav-apk
          path: build/app/outputs/flutter-apk/AutoNav.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/AutoNav.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
